fix: Change property.images[0].url to property.images[0]
Property.images is string[] not Array<{url: string}> in the
interface definition. Fixed TypeScript error:
Property 'url' does not exist on type 'string'.